name: danger_plugin_golden_reporter
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/danger/dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  danger_core:
    path: ../danger_core

dev_dependencies:
  test: ^1.20.2
  mockito: ^5.1.0
  build_runner: ^2.1.8
