name: danger_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/danger/dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  json_annotation: ^4.4.0
  pedantic: ^1.9.0
  test: ^1.20.2
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  mockito: ^5.1.0
  isolate: ^2.1.1
