name: danger_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  json_serializable: ^4.0.2
  build_runner: ^1.11.5
  mockito: ^5.0.0
