name: danger_core
description: Core of Danger Dart, tool to help you reviewing the code.
version: 1.0.0
homepage: https://github.com/danger/dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.1
  json_annotation: ^4.4.0
  test: ^1.20.2
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  mockito: ^5.1.0
  isolate: ^2.1.1
  path: ^1.8.0
