name: danger_plugin_dart_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/danger/dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ">= 1.8.0 < 2.0.0"
  # danger_core: ">= 0.0.1 < 2.0.0"
  danger_core:
    path: ../danger_core

dev_dependencies:
  test: ^1.14.4
