name: danger_dart
description: Danger Dart, tool to help you reviewing the code.
version: 1.0.1
homepage: https://github.com/danger/dart

executables:
  danger_dart:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  args: ^2.3.0
  process_run: ^0.12.3+2
  fimber: ^0.6.5
  path: ^1.8.1
  # danger_core: ">= 1.0.0 < 2.0.0"
  danger_core:
    path: ../danger_core

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
  mockito: ^5.1.0
  build_runner: ^2.1.8
