name: danger_runner
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  args: ^2.0.0
  pedantic: ^1.9.0
  fimber: ^0.6.1
  fimber_io: ^0.6.0
  path: ^1.8.0
  danger_core:
    path: ../danger_core
