# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pull request - pre nullsafety

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Activate command
        run: dart pub global activate --source path packages/danger_dart/

      - name: Install danger_core dependencies
        run: dart pub get
        working-directory: packages/danger_core/

      - name: Install danger_dart dependencies
        run: dart pub get
        working-directory: packages/danger_dart/

      - name: Install example app dependencies
        run: dart pub get
        working-directory: example/pre_nullsafety/

      - name: Run danger local
        run: danger_dart local
        working-directory: example/pre_nullsafety/
